name: build_and_release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: [3.11]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build kanjireader
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: ${{ matrix.python }}
          spec: "scripts/pyinstaller.spec"
          requirements: "requirements.txt"

      - name: Compile install wizard
        uses: Minionguyjpro/Inno-Setup-Action@v1.1.0
        with:
          path: "scripts/setup.iss"
          options: /DVersion="${{ github.ref_name }}"

  release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Release kanjireader
    needs: build
    steps:
      - name: Create release and upload
        uses: meeDamian/github-release@2.0
        with:
          allow_override: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "kanjireader_${{ github.ref_name }}_setup_.exe:dist/kr_setup.exe"
